spring:
  application:
    name: dlrecord
  datasource:
    url: ${DLR_DB_URL}
    username: ${DLR_DB_USER}
    password: ${DLR_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true

    hibernate:
      ddl-auto: update